move:
  ros__parameters:
    plugins:
      - bt_move
    waypoints: ["wheels_zone", "steering_wheels_zone", "body_car_zone", "assembly_zone"]
    waypoint_coords:
      wheels_zone: [0.0, -2.0, 0.0]
      steering_wheels_zone: [1.8, 0.0, 0.0]
      body_car_zone: [0.0, 2.0, 0.0]
      assembly_zone: [-2.0, -0.4, 0.0]

pick:
  ros__parameters:
    plugins:
      - bt_pick

drop:
  ros__parameters:
    plugins:
      - bt_drop